### PR TITLE
Add item notifications backend logic

### PR DESCRIPTION
**Pull request by Ljime**
Created SaleNotification and PriceDropNotifications to check if the item is on sale. The UI component for these will come at a later  time

### CODE REVIEW

**Comment by Ljime** [comment]
Current tests are failing because of the API call limit, will discuss with the team ASAP!

**Review by PyroPoro — COMMENTED** [review]
Code looks good. Remember to add function doc strings.

**Review by AlexChenl3 — DISMISSED** [review]
everything looks good

**Review by DavidZ79 — DISMISSED** [review]
Hey Herman, your code is quite clean and legible. Thanks in advance for dividing up the logic into separate files.

**Review by DavidZ79 — APPROVED** [review]

**Review by AlexChenl3 — APPROVED** [review]

**Pull request merged**
