### PR TITLE
added testing for methods in Price History Use Case

### PR DESCRIPTION
**Pull request by chinchinjim**

### CODE REVIEW

**Review by linajin03 — APPROVED** [review]
It looks like you have a good understanding of how your price history use case functions. Nice on being able to track price history over a certain time period as well. Good work Chin Chin!!

**Review by AlexChenl3 — APPROVED** [review]
code and test file looks good. good job chin chin

**Review by Ljime — APPROVED** [review]
Good job on the tests!

**Comment by chinchinjim** [comment]
thanks everyone :)

**Pull request merged**
