### PR TITLE
Add wishlist read write

### PR DESCRIPTION
**Pull request by Ljime**
Added methods to the Database class that allows us to store and read lists of wishlists data. The data is stored in our database folder with each file containing data to a user's wishlist data.

The main methods to use this database is to call Database.getListOfWishlists to get a user's list of wishlists and Database.saveListOfWishlists to save a user's wishlist

Data is stored in a JSON format, example provided below.
```
{"wishlists":[{"displayedList":[{"priceChange":300.1,"itemName":"Keyboard","desiredPrice":250.0,"itemPrice":300.1,"itemDescription":"Description from amazon (or you write your own)","url":"www.amazon.com\/keyboard","dateAdded":"Mon Nov 14 18:35:59 EST 2022","tags":["computer accesssories","Tech","Mechanical"]},{"priceChange":120.99,"itemName":"Monitor","desiredPrice":85.0,"itemPrice":120.99,"itemDescription":"second monitor dab","url":"www.amazon.com\/monitor","dateAdded":"Mon Nov 14 18:35:59 EST 2022","tags":["computer accesssories","Tech","IPS"]},{"priceChange":40.99,"itemName":"Plushie","desiredPrice":30.0,"itemPrice":40.99,"itemDescription":"Description from amazon (or you write your own)","url":"www.amazon.com\/plushie","dateAdded":"Mon Nov 14 18:35:59 EST 2022","tags":["toys"]}],"name":"Christmas Wishlist","selectedTags":[],"itemList":[{"priceChange":300.1,"itemName":"Keyboard","desiredPrice":250.0,"itemPrice":300.1,"itemDescription":"Description from amazon (or you write your own)","url":"www.amazon.com\/keyboard","dateAdded":"Mon Nov 14 18:35:59 EST 2022","tags":["computer accesssories","Tech","Mechanical"]},{"priceChange":120.99,"itemName":"Monitor","desiredPrice":85.0,"itemPrice":120.99,"itemDescription":"second monitor dab","url":"www.amazon.com\/monitor","dateAdded":"Mon Nov 14 18:35:59 EST 2022","tags":["computer accesssories","Tech","IPS"]},{"priceChange":40.99,"itemName":"Plushie","desiredPrice":30.0,"itemPrice":40.99,"itemDescription":"Description from amazon (or you write your own)","url":"www.amazon.com\/plushie","dateAdded":"Mon Nov 14 18:35:59 EST 2022","tags":["toys"]}],"dateAdded":"Mon Nov 14 18:35:59 EST 2022"}]}
```

Edit: In the file changed history there seems to be some overlap with one of Alex's branches with the empty sorting methods, but those were finished in his PR. I will ask Alex for a PR whenever he is ready to have updated versions

### CODE REVIEW

**Review by chinchinjim — DISMISSED** [review]
nice work. Good job adhering to clean architecture principles 🙂

**Review by AlexChenl3 — DISMISSED** [review]
looks good herman

**Comment by Ljime** [comment]
Hello everyone, I changed a bit on how the user is saved to the database. Previously it was user.writeToDatabase, but now it is just Database.saveUser

**Review by AlexChenl3 — APPROVED** [review]
changes look good judging from the conversation i saw u had with lina

**Review by AlexChenl3 — DISMISSED** [review]
all the code and docstrings looks good, and there doesnt seem to be any merge conflicts. good job herman

**Review by chinchinjim — APPROVED** [review]

**Review by PyroPoro — APPROVED** [review]
looks good to me

**Review by PyroPoro — APPROVED** [review]
reapproving after jdk version change

**Review by AlexChenl3 — APPROVED** [review]

**Review by chinchinjim — APPROVED** [review]

**Pull request merged**
