### PR TITLE
Create add/read user functionality

### PR DESCRIPTION
**Pull request by Ljime**
Created user read and write capabilities in a database class for user management!

### CODE REVIEW

**Review by chinchinjim — DISMISSED** [review]

**Review by AlexChenl3 — APPROVED** [review]

**Review by linajin03 — APPROVED** [review]
good job herman

**Comment by Ljime** [comment]
I factored our data base to store user data in JSON format instead of strings to easier access the data in the future. Looks like this.
image

To add a user to the data base we can use the User.writeToDatabase function and getting a user can be achieved by using the Database's static read user function.

**Review by chinchinjim — APPROVED** [review]
Looks good, will make the code more readable so it is less complicated for us to work with. Thanks Herman

**Comment by chinchinjim** [comment]
sorry i thought closing the pull review approved it mb

**Review by linajin03 — APPROVED** [review]

**Review by AlexChenl3 — APPROVED** [review]
goods look herman!

**Pull request merged**
