### PR TITLE
Item price history

### PR DESCRIPTION
**Pull request by chinchinjim**
Added backend functions for the Price History use case, including: daily price update tracking, formatting for future graphing purposes, price comparison over time calculations, some more price comparison functions.

Modified item class to add a priceHistoryData field

I haven't put it into clean architecture yet; as of now this is just the bare bones logic. Also have not implemented graphing the price history chart yet on this (need to collab with frontend folks). Will add testing in a future PR

Thanks :)

### CODE REVIEW

**Review by AlexChenl3 — DISMISSED** [review]
functions and docstrings look good. looking forwards to ur implementation of graphing price history chart!

**Comment by kevinle623** [comment]
Hello, when I tried merging the main to pull request and tested it out, it seems that the TimerTask cause the code to keep on running and never stops whenever an Item Object is initialized. Let me know if I miss used the implementation. Thanks.
image

However, when I comment out the TimerTask implementation it runs and stops the code after execution. Not sure what the issue is as it might be a problem on my end.

**Comment by Ljime** [comment]
> Hello, when I tried merging the main to pull request and tested it out, it seems that the TimerTask cause the code to keep on running and never stops whenever an Item Object is initialized. Let me know if I miss used the implementation. Thanks. image
> 
> However, when I comment out the TimerTask implementation it runs and stops the code after execution. Not sure what the issue is as it might be a problem on my end.

The program keeping on running should be fine it would be bad if it stopped since that would mean that the timer is not running. The timer should be running for the duration of the program

**Review by Ljime — CHANGES_REQUESTED** [review]
Overall, the logic for this use case should work well when we integrate it with the front-end part. There are just a few niche cases I thought were important to address to prevent future issues. Good job!

**Comment by chinchinjim** [comment]
Thanks for the suggestions @Ljime ! I've implemented the changes and added a field for the priceHistoryDates

**Review by AlexChenl3 — APPROVED** [review]

**Review by PyroPoro — APPROVED** [review]

**Pull request merged**
