### PR TITLE
Added user delete function

### PR DESCRIPTION
**Pull request by Ljime**
Added user delete function

### CODE REVIEW

**Review by linajin03 — DISMISSED** [review]
Thanks Herman! This should help with the functionality of my UserRegister tests

**Review by DavidZ79 — DISMISSED** [review]
good job herman

**Review by kevinle623 — DISMISSED** [review]
fixed merge conflict, looks good to me

**Review by DavidZ79 — APPROVED** [review]
good job herman

**Review by linajin03 — APPROVED** [review]
Thanks!

**Review by AlexChenl3 — APPROVED** [review]
everything looks good hermanns! good job

**Pull request merged**
